package com.mavyy.localyuki.foundation.subsystem

/** Architectural identities, not declarations that implementations are available. */
enum class CoreSubsystemId {
    IDENTITY_CONTINUITY_CORE, PERSONALITY_CAPSULE, YUKI_STATE, TEMPORAL_GROUNDING,
    MEMORY_ENGINE, SEMANTIC_RECALL, AFFECTIVE_SYSTEM, COGNITIVE_WORKSPACE,
    REALITY_VERIFICATION, EMBODIED_CAPABILITY_REGISTRY, EXECUTIVE_ACTION_CONTROL,
    RESOURCE_GOVERNOR, SCHEDULER_PROACTIVE, SLEEP_RECOVERY, PERCEPTION,
    SYSTEM_ONE_ENGINE, SYSTEM_TWO_ENGINE, LANGUAGE_EXPRESSION_ENGINE,
    SPECIALIST_ENGINE, VAULT_EXPORT
}

enum class SubsystemRole { AUTHORITY, COORDINATOR, CONTROL, GROUNDING, ADVISORY }
